-- EMPNO, ENAME, SAL, DEPTNO 부서번호 10번과 20번 출력
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 20;

-- 집합 연산자 사용하여 출력하기(출력 열의 자료형 순서가 다를때) 5-32
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 10
UNION
SELECT ENAME, EMPNO, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 20;

-- 행의 순서가 다르지만 문자나 숫자의 형태는 맞춘 경우
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 10
UNION
SELECT SAL, JOB, DEPTNO, SAL FROM EMP
WHERE DEPTNO = 20;

-- 차집합
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 10;

-- 교집합
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 10;
