DROP TABLE PERSON;

CREATE TABLE PERSON(
    ID      NUMBER(5),
    NAME    VARCHAR2(30) );
    
SELECT * FROM PERSON;
ALTER TABLE PERSON ADD HP VARCHAR2(20);
ALTER TABLE PERSON RENAME COLUMN HP TO TEL;
ALTER TABLE PERSON MODIFY TEL VARCHAR2(13);
ALTER TABLE PERSON DROP COLUMN TEL;
