-- P.239 Q1
SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND SAL > 2000
ORDER BY E.DEPTNO, D.DNAME;

SELECT DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E NATURAL JOIN DEPT D
WHERE SAL > 2000
ORDER BY DEPTNO, D.DNAME;

-- P.239 Q2
SELECT E.DEPTNO, D.DNAME, ROUND(AVG(SAL),0), MAX(SAL), MIN(SAL), COUNT(*)
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY E.DEPTNO, D.DNAME;

SELECT DEPTNO, D.DNAME, ROUND(AVG(SAL),0), MAX(SAL), MIN(SAL), COUNT(*)
FROM EMP E NATURAL JOIN DEPT D
GROUP BY DEPTNO, D.DNAME;

-- P.239 Q3
SELECT NVL(E.DEPTNO, 40) AS "DEPTNO", D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO ORDER BY DEPTNO, D.DNAME;

SELECT NVL(E.DEPTNO, 40) AS "DEPTNO", D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E RIGHT JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
ORDER BY DEPTNO, D.DNAME;

-- P.240 Q4
SELECT D.DEPTNO, D.DNAME,E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO,S.LOSAL,
S.HISAL, S.GRADE,E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME
  FROM EMP E, DEPT D, SALGRADE S, EMP E2
  WHERE E.DEPTNO(+) = D.DEPTNO
        AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
        AND E.MGR = E2.EMPNO(+)
ORDER BY D.DEPTNO, E.EMPNO;

SELECT D.DEPTNO, D.DNAME,E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO,S.LOSAL,
S.HISAL, S.GRADE,E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME
  FROM DEPT D LEFT JOIN EMP E
                ON (E.DEPTNO = D.DEPTNO)
              LEFT JOIN SALGRADE S
                ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
              LEFT JOIN EMP E2
                ON (E.MGR = E2.EMPNO)
ORDER BY D.DEPTNO, E.EMPNO; 
