-- 실습 8-8 자체 JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.ENAME AS "매니저"
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.MGR;

-- 자체 JOIN으로 같은 감독의 다른 영화 찾기
-- COLUMN = 영화제목, 감독
SELECT M1.TITLE AS "영화제목", M2.DIRECTOR AS "감독"
FROM MOVIES M1, MOVIES M2
WHERE M1.DIRECTOR = M2.DIRECTOR AND M1.TITLE != M2.TITLE
ORDER BY M2.DIRECTOR ASC;

-- 같은 장르인 영화 찾기 COLUMN = 제목, 장르
SELECT M1.TITLE AS "영화제목", M2.GENRE AS "장르"
FROM MOVIES M1, MOVIES M2
WHERE M1.GENRE = M2.GENRE AND M1.TITLE != M2.TITLE
ORDER BY M2.TITLE ASC;

-- P.228 LEFT OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.EMPNO, E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.MGR(+);
-- P.228 RIGHT OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.EMPNO, E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR(+) = E2.MGR;
