-- 시스템 권한 부여
GRANT [시스템 권한] TO [사용자이름/롤(ROLE)이름/PUBLIC] [WITH ADMIN OPTION];
-- 시스템 취소 권한
REVOKE [시스템 권한] [사용자이름/롤(ROLE)이름/PUBLIC];

-- 시스템 계정으로 접속하여 유저 만들기
CREATE USER ORCLSTUDY IDENTIFIED BY ORACLE;
-- 권한 부여
GRANT CREATE SESSION TO ORCLSTUDY;
SELECT * FROM ALL_USERS WHERE USERNAME = 'ORCLSTUDY';

-- 사용자 삭제
DROP USER ORCLSTUDY;
COMMIT;
-- 가지고 있던 권한까지 전부 없애려고 했다면?
DROP USER ORCLSTUDY CASCADE;
COMMIT;

-- 실습 15-7
CREATE USER ORCLSTUDY IDENTIFIED BY ORACLE;
GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO ORCLSTUDY;

-- 권한 제거
REVOKE RESOURCE FROM ORCLSTUDY;

-- 실습 15-14 ROLE 사용
CREATE ROLE ROLESTUDY;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM TO ROLESTUDY;
GRANT ROLESTUDY TO ORCLSTUDY;
-- 권한 ROLE을 이용해 한 번에 제거
REVOKE ROLESTUDY FROM ORCLSTUDY;
-- ORCLSTUDY에 부여된 권한 조사
CONN ORCLSTUDY/ORACLE
SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;
