SELECT * FROM EMP;
SELECT EMPNO EMPLOYEE_NO,
       ENAME EMPLOYEE_NAME,
       MGR MANAGER,
       SAL SALARY,
       COMM COMMISSION,
       DEPTNO DEPARTMENT_NO FROM EMP ORDER BY DEPTNO DESC, ENAME;
