-- 실습 6-47 DECODE문
SELECT EMPNO, ENAME, JOB, SAL,
    DECODE(JOB,
            'MANAGER', SAL*1,1,
            'SALESMAN', SAL*1.05,
            'ANALYST', SAL,
            SAL*1.03) AS UPSAL
FROM EMP;

-- 특정조건
SELECT EMPNO, ENAME, SAL,
    CASE 
        WHEN SAL >= 3000 THEN '상위권'
        WHEN SAL > 1000 AND SAL < 3000 THEN '중위권'
        ELSE '하위권'
    END
FROM EMP;

-- WHEN~ CASE문 사용
SELECT EMPNO, ENAME, JOB, SAL,
    CASE JOB
        WHEN 'MANAGER' THEN SAL*1.1
        WHEN 'SALESMAN' THEN SAL*1.05
        WHEN 'ANALYST' THEN SAL
        ELSE SAL*1.03
    END AS UPSAL
FROM EMP;

-- P175 Q3
SELECT EMPNO, ENAME, HIREDATE,
    TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3), '월요일'), 'YYYY-MM-DD') AS R_JOB,
    NVL2(COMM, TO_CHAR(COMM), 'N/A')
FROM EMP;

-- P175 Q4
SELECT EMPNO, ENAME, MGR,
    CASE 
        WHEN MGR IS NULL THEN 0000
        WHEN SUBSTR(TO_CHAR(MGR), 1, 2) = '75' THEN 5555
        WHEN SUBSTR(TO_CHAR(MGR), 1, 2) = '76' THEN 6666
        WHEN SUBSTR(TO_CHAR(MGR), 1, 2) = '77' THEN 7777
        WHEN SUBSTR(TO_CHAR(MGR), 1, 2) = '78' THEN 8888
        ELSE MGR
    END AS CHG_MGR
FROM EMP;
