-- ALTER TABLE
CREATE TABLE EMP_ALTER AS SELECT * FROM EMP;
SELECT * FROM EMP_ALTER;

-- COLUMN 추가 - ADD
ALTER TABLE EMP_ALTER
ADD HP VARCHAR2(20);

-- COLUMN명 변경 - RENAME
ALTER TABLE EMP_ALTER
RENAME COLUMN HP TO TEL;

-- COLUMN 길이 변경
ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(5);
DESC EMP_ALTER;

-- COLUMN 삭제
ALTER TABLE EMP_ALTER
DROP COLUMN TEL;
SELECT * FROM EMP_ALTER;
