-- 실습 10-15 데이터 전체 수정
CREATE TABLE DEPT_TEMP2 AS SELECT * FROM DEPT;
COMMIT;
SELECT * FROM DEPT_TEMP2;
-- 실습 10-16
UPDATE DEPT_TEMP2 SET LOC = 'SEOUL'; ROLLBACK;
SELECT * FROM DEPT_TEMP2;

-- 실습 10-18 일부분만 수정
UPDATE DEPT_TEMP2 SET LOC = 'NEW YORK' WHERE DEPTNO = 10;
UPDATE DEPT_TEMP2 SET LOC = 'DALLAS' WHERE DEPTNO = 20;
UPDATE DEPT_TEMP2 SET LOC = 'CHICAGO' WHERE DEPTNO = 30;
UPDATE DEPT_TEMP2 SET LOC = 'BOSTON' WHERE DEPTNO = 40;

-- 실습 10-19 서브쿼리로 데이터 일부분 수정
UPDATE DEPT_TEMP2 SET (DNAME, LOC)
= (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = 40) WHERE DEPTNO = 40;
SELECT * FROM DEPT_TEMP2;

-- 실습 10-20 서브쿼리로 열 하나하나 수정
UPDATE DEPT_TEMP2 SET
DNAME = (SELECT DNAME FROM DEPT WHERE DEPTNO = 40),
LOC = (SELECT LOC FROM DEPT WHERE DEPTNO = 40) WHERE DEPTNO = 40;
SELECT * FROM DEPT_TEMP2;

-- 테이블 삭제 및 복사 생성
DROP TABLE EMP_TEMP;
CREATE TABLE EMP_TEMP AS SELECT * FROM EMP;
SELECT * FROM EMP_TEMP;

-- 데이터 일부분만 삭제하기
DELETE FROM EMP_TEMP WHERE EMPNO = 7369;

-- SUBQUERY 사용하여 데이터 일부 삭제
DELETE FROM EMP_TEMP2
 WHERE EMPNO IN (SELECT E.EMPNO FROM EMP_TEMP2 E, SALGRADE S
                 WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
	                AND S. GRADE = 3 AND DEPTNO = 30);
SELECT * FROM EMP_TEMP2;
