-- 실습 7-24
SELECT DEPTNO, JOB, COUNT(*), MAX(SAL), SUM(SAL), ROUND(AVG(SAL),2) FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;
-- ROLLUP : 각 개별 항목의 합계치를 보여줌, 그룹화 결과를 의미
SELECT DEPTNO, JOB, COUNT(*), MAX(SAL), SUM(SAL), ROUND(AVG(SAL),2) FROM EMP
GROUP BY ROLLUP(DEPTNO, JOB);
-- CUBE : ROLLUP에서 중간중간에 나오던 정보들을 한 번에 모아서 출력해줌
SELECT DEPTNO, JOB, COUNT(*), MAX(SAL), SUM(SAL), ROUND(AVG(SAL),2) FROM EMP
GROUP BY CUBE(DEPTNO, JOB)
ORDER BY DEPTNO, JOB;

-- 실습 7-36 PIVOT(행과 열의 교환)
SELECT DEPTNO, JOB, MAX(SAL) FROM EMP 
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

SELECT * FROM (SELECT DEPTNO, JOB, SAL FROM EMP)
    PIVOT(MAX(SAL) FOR DEPTNO IN (10, 20, 30))
ORDER BY JOB;

-- 실습 7-37 부서별, 직책별 최고 급여를 2차원 표 형태로 출력하세요.
SELECT * FROM (SELECT JOB, DEPTNO, SAL FROM EMP)
    PIVOT(MAX(SAL) FOR JOB IN ('CLERK' AS CLERK,
                               'SALESMAN' AS SALESMAN,
                               'PRESIDENT' AS PRESIDENT,
                               'MANAGER' AS MANAGER,
                               'ANALYST' AS ANALYST)
         )
ORDER BY DEPTNO;
