-- SUM, COUNT, MAX, MIN, AVG 함수
SELECT COUNT(SAL) FROM EMP;
SELECT MAX(SAL) FROM EMP;
SELECT MIN(SAL) FROM EMP;
SELECT ROUND(AVG(SAL), 2) FROM EMP;

-- 집합연산 다중행연산 묶어서 처리하기
SELECT ROUND(AVG(SAL),2) FROM EMP
WHERE DEPTNO = 30;

SELECT DEPTNO, ROUND(AVG(SAL),2) FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

-- 부서별 급여의 합
SELECT DEPTNO, SUM(SAL) FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

-- 급여의 합계
SELECT SUM(DISTINCT SAL),
       SUM(ALL SAL),
       SUM(SAL)
FROM EMP;
-- 인원
SELECT COUNT (*) FROM EMP;
-- 부서별 인원
SELECT DEPTNO, COUNT (*) FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;
