-- Q1
SELECT GENRE, COUNT (*) FROM MOVIES GROUP BY GENRE ORDER BY COUNT (*) DESC;
-- Q2
SELECT TITLE FROM MOVIES WHERE RUNTIME >= 130 ORDER BY TITLE;
-- Q3
SELECT 
    SUM(CASE
        WHEN RELEASE_DATE <= TO_DATE('2014-12-31', 'YYYY-MM-DD') THEN 1
        ELSE 0
        END) AS "2014 이전",
    SUM(CASE
        WHEN RELEASE_DATE > TO_DATE('2014-12-31', 'YYYY-MM-DD') THEN 1
        ELSE 0
        END) AS "2015 이후"
FROM MOVIES;
-- Q4
SELECT AVG(RUNTIME) FROM MOVIES;
-- Q5
SELECT TITLE FROM MOVIES
WHERE RUNTIME = (SELECT MAX(RUNTIME) FROM MOVIES)
   OR RUNTIME = (SELECT MIN(RUNTIME) FROM MOVIES);
