-- P174 Q1
SELECT EMPNO, 
       ENAME,
       SUBSTR(EMPNO, 1, 2) || LPAD('*', LENGTH(EMPNO) - 2, '*') AS MASKING_EMPNO,
       SUBSTR(ENAME, 1, 1) || LPAD('*', LENGTH(ENAME) - 1, '*') AS MASKING_ENAME
FROM EMP
WHERE LENGTH(ENAME) >= 5 AND LENGTH(ENAME) < 6;

-- P175 Q3
SELECT EMPNO, ENAME, HIREDATE,
    TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3), '월요일'), 'YYYY-MM-DD') AS R_JOB,
    NVL2(COMM, TO_CHAR(COMM), 'N/A')
FROM EMP;

-- P175 Q4
SELECT EMPNO, ENAME, MGR,
    CASE 
        WHEN MGR IS NULL THEN 0000
        WHEN SUBSTR(TO_CHAR(MGR), 1, 2) = '75' THEN 5555
        WHEN SUBSTR(TO_CHAR(MGR), 1, 2) = '76' THEN 6666
        WHEN SUBSTR(TO_CHAR(MGR), 1, 2) = '77' THEN 7777
        WHEN SUBSTR(TO_CHAR(MGR), 1, 2) = '78' THEN 8888
        ELSE MGR
    END AS CHG_MGR
FROM EMP;
