-- HAVING절 : GROUP BY절의 조건
SELECT DEPTNO, JOB, ROUND(AVG(SAL), 2) FROM EMP
    GROUP BY DEPTNO, JOB
    HAVING ROUND(AVG(SAL),2) >= 2000
    ORDER BY DEPTNO, JOB;
    
-- WHERE절과 HAVING절을 같이 사용해보기
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP
WHERE SAL = 3000
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;
