-- P.232 NATURAL JOIN
SELECT DEPTNO, E.ENAME, D.DNAME
FROM EMP E NATURAL JOIN DEPT D
ORDER BY DEPTNO, E.EMPNO;

-- P.233 JOIN ~ USING
SELECT E.ENAME, DEPTNO, D.DNAME
FROM EMP E JOIN DEPT D USING (DEPTNO);

-- P.234 JOIN ~ ON
SELECT E.DEPTNO, E.ENAME, D.DNAME
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
ORDER BY E.DEPTNO, E.ENAME DESC;
