SELECT * FROM EMP WHERE ENAME LIKE 'S%';
SELECT * FROM EMP WHERE ENAME LIKE '%S%';

SELECT * FROM EMP WHERE ENAME LIKE '%_L%';
SELECT * FROM EMP WHERE ENAME NOT LIKE '%AM%';

--COMM이 NULL 값인 데이터만 출력하려면?
SELECT * FROM EMP WHERE COMM IS NULL;
--상관이 없는 직원? = MGR 값이 NULL 인 직원
SELECT * FROM EMP WHERE MGR IS NULL;

SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME) FROM EMP;
SELECT * FROM EMP WHERE UPPER(ENAME) = UPPER('king');
