--테이블 삭제
DROP TABLE EMP_DDL;
--테이블 생성
CREATE TABLE EMP_DDL
(
    EMPNO   NUMBER(4),
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9)
);
--검색
SELECT * FROM EMP_DDL;
--삽입
INSERT INTO EMP_DDL VALUES (1, 'TOM', 'MANAGER');
INSERT INTO EMP_DDL VALUES (2, '홍길동', '대리');
