-- 실습 14-29 PRIMARY KEY 설정
CREATE TABLE TABLE_PK(
    LOGIN_ID  VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL       VARCHAR2(20)
);

DESC TABLE_PK;
SELECT * FROM TABLE_PK;
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_PK%';

-- 실습 14-31 PRIMARY KEY를 통해 생성된 INDEX 확인
SELECT INDEX_NAME, TABLE_OWNER, TABLE_NAME FROM USER_INDEXES
WHERE TABLE_NAME LIKE 'TABLE_PK%';

-- 실습 14-32 제약에 이름 넣기
CREATE TABLE TABLE_PK2(
    LOGIN_ID  VARCHAR2(20) CONSTRAINT TBLPK2_LGNID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLPK2_LGNPW_NN NOT NULL,
    TEL       VARCHAR2(20) );
DESC TABLE_PK2;
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_PK%';

-- 실습 14-33 테이블에 값 입력
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01','PWD01','010-1234-5678');
SELECT * FROM TABLE_PK;

-- 실습 14-35 NULL 값 명시적 입력
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES(NULL, 'PWD02', '010-2345-6789');

-- 실습 14-36 NULL 값 암시적 입력
INSERT INTO TABLE_PK(LOGIN_PWD, TEL)
VALUES('PWD02', '010-2345-6789');

-- 테이블 작성의 다른 방법
CREATE TABLE TABLE_PK3(
    LOGIN_ID  VARCHAR2(20),
    LOGIN_PWD VARCHAR2(20),
    TEL       VARCHAR2(20),
    PRIMARY KEY(LOGIN_ID),
    CONSTRAINT CONSTRAINT_NAME UNIQUE(LOGIN_PWD) -- 이름 지정하는 방식
);
