-- Unique 제약 조건
-- 14-14 중복되지 않는 제약 UNIQUE
CREATE TABLE TABLE_UNIQUE (
    LOGIN_ID  VARCHAR2(20) UNIQUE,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL       VARCHAR2(20)
);
DESC TABLE_UNIQUE;

-- 실습 14-15 데이터 사전 뷰
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_UNIQUE';

-- 실습 14-16~18 중복 데이터 넣어보기
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01','PWD01','010-1234-5678');
SELECT * FROM TABLE_UNIQUE;

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01','PWD01','010-1234-5678');

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_02','PWD01','010-1234-5678');

-- 실습 14-21~22 테이블 생성 시 UNIQUE 제약 조건 설정
DROP TABLE TABLE_UNIQUE2;
CREATE TABLE TABLE_UNIQUE2(
    LOGIN_ID  VARCHAR2(20) CONSTRAINT AAA_LOGIN_UNQ UNIQUE,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT BBB_LOGIN_PWNN NOT NULL,
    TEL       VARCHAR2(20) );

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';

-- 실습 14-19~20 UNIQUE 열에 NULL 값을 입력하기
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES(NULL, 'PWD01', '010-2345-6789');
SELECT * FROM TABLE_UNIQUE;

UPDATE TABLE_UNIQUE SET LOGIN_ID = 'TEST_ID_01'
WHERE LOGIN_ID IS NULL;

-- 실습 14-24~27 이미 만들어진 테이블에 제약 조건 추가
UPDATE TABLE_UNIQUE SET TEL = NULL;
SELECT * FROM TABLE_UNIQUE;

ALTER TABLE TABLE_UNIQUE MODIFY(TEL UNIQUE);

ALTER TABLE TABLE_UNIQUE2
MODIFY(TEL CONSTRAINT CCC_TEL_UNQ UNIQUE);
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';

ALTER TABLE TABLE_UNIQUE2
RENAME CONSTRAINT CCC_TEL_UNQ TO DDD_TEL_UNQ;

-- 실습 14-28 제약 조건 삭제
ALTER TABLE TABLE_UNIQUE2 DROP CONSTRAINT DDD_TEL_UNQ;
