-- 실습 14-37 EMP 테이블과 DEPT 테이블의 상호 간 제약 조건 살펴보기
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, R_OWNER, R_CONSTRAINT_NAME
    FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('EMP', 'DEPT');

-- 테이블 간의 연관(R) 만들기
-- 실습 14-39 DEPT_FK 테이블 생성
CREATE TABLE DEPT_FK(
    DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13) );

CREATE TABLE EMP_FK(
    EMPNO    NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME    VARCHAR2(10),
    DEPTNO   NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO)
);

DROP TABLE EMP_FK;
DROP TABLE DEPT_FK;

-- 열 데이터 삭제 시 참조 데이터 함께 삭제
CONSTRAINT [제약 조건 이름] REFERENCES 참조 테이블(열) ON DELETE CASCADE
-- 열 데이터 삭제 시 참조 데이터 NULL로 수정
CONSTRAINT [제약 조건 이름] REFERENCES 참조 테이블(열) ON DELETE SET NULL

CREATE TABLE DEPT_FK(
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13) );

CREATE TABLE EMP_FK(
    EMPNO    NUMBER(4) PRIMARY KEY,
    ENAME    VARCHAR2(10),
    DEPTNO   NUMBER(2) REFERENCES DEPT_FK (DEPTNO)
);
SELECT * FROM EMP_FK;
SELECT * FROM DEPT_FK;

-- FOREIGN KEY 데이터 기입
INSERT INTO DEPT_FK VALUES (10, '개발1팀', '안동');
INSERT INTO EMP_FK VALUES(1, '홍길동', 10);
-- FOREIGN KEY 데이터 삭제 (직원)
DELETE FROM EMP_FK WHERE DEPTNO = 10;
DELETE FROM DEPT_FK WHERE DEPTNO = 10;
