-- 14-45 CHECK 제약 조건 설정
CREATE TABLE TABLE_CHECK(
    LOGIN_ID  VARCHAR2(20) CONSTRAINT TBLCK_LGNID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCK_LGNPW_CK
        CHECK (LENGTH(LOGIN_PWD)>3),
    TEL       VARCHAR2(20)
);

-- CHECK 제약 조건에 맞는 값 기입 후 조건 확인
INSERT INTO TABLE_CHECK VALUES ('TEST_ID', '1234', '010-1234-5678');
SELECT * FROM TABLE_CHECK;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_CHECK';

-- DEFAULT 지정하여 테이블 생성 및 INSERT문 확인
CREATE TABLE TABLE_DEFAULT(
    LOGIN_ID  VARCHAR2(20) CONSTRAINT TBLCK2_LGNID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) DEFAULT '1234',
    TEL       VARCHAR2(20)
);
DESC TABLE_DEFAULT;
SELECT * FROM TABLE_DEFAULT;

-- INSERT문 확인
INSERT INTO TABLE_DEFAULT VALUES ('TEST_ID',NULL,'010-1234-5678');
INSERT INTO TABLE_DEFAULT (LOGIN_ID, TEL) VALUES ('TEST_ID2', '010-1234-5678');

-- 제약 조건 비활성화
ALTER TABLE [테이블 이름]
DISABLE [NOVALIDATE / VALIDATE(선택)] CONSTRAINT [제약조건 이름];
-- 제약 조건 활성화
ALTER TABLE [테이블 이름]
ENABLE [NOVALIDATE / VALIDATE(선택)] CONSTRAINT [제약조건 이름];
