DECLARE
    V_TAX CONSTANT NUMBER(1) :=3;
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_TEX : ' || V_TAX);
END;
/

-- PL/SQL 변수의 기본값 설정 가능
DECLARE
    V_DEPTNO NUMBER(2) DEFAULT 10;
BEGIN
    -- V_DEPTNO := 50;
    DBMS_OUTPUT.PUT_LINE('V_DEPTNO : ' || V_DEPTNO);
END;
/

-- 변수에 NOT NULL 설정하고 값 대입 후 출력
DECLARE
    V_DEPTNO NUMBER(2) NOT NULL := 10;
BEGIN
    DBMS_OUTPUT.PUT_LINE(V_DEPTNO);
END;
/

-- 16-9 참조형 변수에 값 대입 후 출력
DECLARE
		-- DEPT 테이블의 DEPTNO COLUMN 자료형을 참조하여 가져왔음을 의미
    V_DEPTNO DEPT.DEPTNO%TYPE DEFAULT 50;
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_DEPTNO : ' || V_DEPTNO);
END;
/

-- 실습 16-10 %ROWTYPE 이용
DECLARE
    V_DEPT_ROW DEPT%ROWTYPE;
BEGIN
    SELECT DEPTNO, DNAME, LOC INTO V_DEPT_ROW
        FROM DEPT
    WHERE DEPTNO = 40;
    DBMS_OUTPUT.PUT_LINE('DEPTNO : ' || V_DEPT_ROW.DEPTNO);
    DBMS_OUTPUT.PUT_LINE('DNAME : ' || V_DEPT_ROW.DNAME);
    DBMS_OUTPUT.PUT_LINE('LOC : ' || V_DEPT_ROW.LOC);
END;
/
