-- 실습 19-42~ TRIGGER 관리/정보조회/변경
SELECT TRIGGER_NAME, TRIGGER_TYPE, TRIGGERING_EVENT, TABLE_NAME, STATUS
    FROM USER_TRIGGERS;
-- 트리거 변경
/* ALTER TRIGGER 트리거 이름 ENABLE | DISABLE;
   ALTER TRIGGER 트리거 이름 ENABLE | DISABLE ALL TRIGGERS; */
-- 트리거 삭제
DROP TRIGGER TRG_EMP_LOG;
