-- PART 테이블 삽입 내용
INSERT INTO PART VALUES('Panasonic18650_Cell',10);
INSERT INTO PART VALUES('Panasonic2170_Cell',10);
INSERT INTO PART VALUES('TeslaModelS_BP',10);
INSERT INTO PART VALUES('TeslaModel3_BP',10);
INSERT INTO PART VALUES('TeslaModelX_BP',10);
INSERT INTO PART VALUES('TeslaModelY_BP',10);
INSERT INTO PART VALUES('TeslaModelS_Front_Motor',10);
INSERT INTO PART VALUES('TeslaModel3_Front_Motor',10);
INSERT INTO PART VALUES('TeslaModelX_Front_Motor',10);
INSERT INTO PART VALUES('TeslaModelY_Front_Motor',10);
INSERT INTO PART VALUES('TeslaModelS_Rear_Motor',10);
INSERT INTO PART VALUES('TeslaModel3_Rear_PMSM',10);
INSERT INTO PART VALUES('TeslaModelX_Rear_Motor',10);
INSERT INTO PART VALUES('TeslaModelY_Rear_PMSM',10);
INSERT INTO PART VALUES('TeslaModelS_Inverter',10);
INSERT INTO PART VALUES('TeslaModel3_Inverter',10);
INSERT INTO PART VALUES('TeslaModelX_Inverter',10);
INSERT INTO PART VALUES('TeslaModelY_Inverter',10);
INSERT INTO PART VALUES('TeslaModelS_DriveUnit',10);
INSERT INTO PART VALUES('TeslaModel3_DriveUnit',10);
INSERT INTO PART VALUES('TeslaModelX_DriveUnit',10);
INSERT INTO PART VALUES('TeslaModelY_DriveUnit',10);
INSERT INTO PART VALUES('Tesla_FSD_Computer',10);

-- CARNAME 테이블 삽입 내용
INSERT INTO CARNAME VALUES('테슬라 모델 S',0);
INSERT INTO CARNAME VALUES('테슬라 모델 3',0);
INSERT INTO CARNAME VALUES('테슬라 모델 X',0);
INSERT INTO CARNAME VALUES('테슬라 모델 Y',0);
